---
name: Pull Request NPM Checks
on: [pull_request]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  npm-test:
    name: NPM test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Prepare Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Run `npm ci`
        # See the PR below for why `--legacy-peer-deps`` is needed.
        # https://github.com/netdata/dashboard/pull/467
        run: npm ci --legacy-peer-deps
      - name: Run `npm test`
        run: npm test
  npm-lint:
    name: NPM lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Prepare Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Run `npm ci`
        run: npm ci --legacy-peer-deps
      - name: Run `npm run lint`
        run: npm run lint
